/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//Testing of bits (&)
//Setting of bits (|)
//Clearing of bits (~ and &)
//Toggling of bits (^)

int main(void)
{
	printf("Enable led on PD12");
	uint32_t *pClkCtrlReg 			= (uint32_t*)0x40023830;
	uint32_t *pGpiodModeReg 		= (uint32_t*)0x40020C00;
	uint32_t *pGpiodOutputDataReg 	= (uint32_t*)0x40020C14;

	// enable the clock for GPIOD peripheral in the AHB1ENR
	*pClkCtrlReg 		 |= 	0x08;
	// create mask and set bits accordingly
	*pGpiodModeReg 		 &= 	0xFFFFF3FF;
	*pGpiodModeReg 		 |= 	0x00000400;
	*pGpiodOutputDataReg |= 	0x0020;
	// clear the bits
	*pGpiodModeReg 		 &= 	0xFFFFFFFF;
	*pGpiodOutputDataReg &= 	0x0000;

    /* Loop forever */
	for(;;);
}
